"""update schedule table again  

Revision ID: 015cc8f48076
Revises: b488133405a7
Create Date: 2026-01-23 21:51:25.272447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015cc8f48076'
down_revision: Union[str, Sequence[str], None] = 'b488133405a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Use IF NOT EXISTS to safely skip already-existing columns
    op.execute("ALTER TABLE schedules ADD COLUMN IF NOT EXISTS schedule_id INTEGER NOT NULL DEFAULT 0")
    op.execute("ALTER TABLE schedules ADD COLUMN IF NOT EXISTS lecture_id INTEGER")
    # Add any other columns that were in this migration the same way


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'lecture_id')
    op.drop_column('schedules', 'schedule_id')
    # ### end Alembic commands ###
