"""update schedule table again  

Revision ID: 015cc8f48076
Revises: b488133405a7
Create Date: 2026-01-23 21:51:25.272447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015cc8f48076'
down_revision: Union[str, Sequence[str], None] = 'b488133405a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.add_column('schedules', sa.Column('lecture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedules', 'lectures', ['lecture_id'], ['lecture_id'])
    op.drop_column('schedules', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'lecture_id')
    op.drop_column('schedules', 'schedule_id')
    # ### end Alembic commands ###
