"""add_pipeline_fields

Revision ID: 43fad2e23673
Revises: 015cc8f48076
Create Date: 2026-04-07 15:41:29.818749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '43fad2e23673'
down_revision: Union[str, Sequence[str], None] = '015cc8f48076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('script_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lectures', sa.Column('num_steps', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('lectures', sa.Column('audio_cfg', sa.Float(), nullable=False, server_default='0'))
    op.add_column('lectures', sa.Column('text_cfg', sa.Float(), nullable=False, server_default='0'))
    op.add_column('lectures', sa.Column('seed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('lectures', sa.Column('preset', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('lectures', sa.Column('avatar_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('lectures', sa.Column('output_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lectures', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lectures', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('lectures', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # Remove server defaults so future inserts must supply values explicitly
    op.alter_column('lectures', 'num_steps', server_default=None)
    op.alter_column('lectures', 'audio_cfg', server_default=None)
    op.alter_column('lectures', 'text_cfg', server_default=None)
    op.alter_column('lectures', 'seed', server_default=None)
    op.alter_column('lectures', 'preset', server_default=None)
    op.alter_column('lectures', 'avatar_backend', server_default=None)
    op.add_column('teachers', sa.Column('onboarding_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'))
    op.alter_column('teachers', 'onboarding_status', server_default=None)
    op.add_column('teachers', sa.Column('preprocessed_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('teachers', sa.Column('cached_voice_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'cached_voice_path')
    op.drop_column('teachers', 'preprocessed_image_path')
    op.drop_column('teachers', 'onboarding_status')
    op.drop_column('lectures', 'completed_at')
    op.drop_column('lectures', 'started_at')
    op.drop_column('lectures', 'error_message')
    op.drop_column('lectures', 'output_video_path')
    op.drop_column('lectures', 'avatar_backend')
    op.drop_column('lectures', 'preset')
    op.drop_column('lectures', 'seed')
    op.drop_column('lectures', 'text_cfg')
    op.drop_column('lectures', 'audio_cfg')
    op.drop_column('lectures', 'num_steps')
    op.drop_column('lectures', 'script_path')
    # ### end Alembic commands ###
