"""add_extracted_txt_path_to_lecture

Revision ID: 5d72c48fdc2b
Revises: 96fa662d89df
Create Date: 2026-05-27 14:36:16.819449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d72c48fdc2b'
down_revision: Union[str, Sequence[str], None] = '96fa662d89df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('extracted_txt_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lectures', 'extracted_txt_path')
    # ### end Alembic commands ###
