"""add_lecture_pipelines_table

Revision ID: 98245adc4da6
Revises: 43fad2e23673
Create Date: 2026-04-08 02:25:46.479540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
import sqlmodel  # ← add this line
# revision identifiers, used by Alembic.
revision: str = '98245adc4da6'
down_revision: Union[str, Sequence[str], None] = '43fad2e23673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_pipelines',
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'COMPLETED', 'FAILED', name='pipelinestatus'), nullable=False),
    sa.Column('script_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('audio_cfg', sa.Float(), nullable=False),
    sa.Column('text_cfg', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('preset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.lecture_id'], ),
    sa.PrimaryKeyConstraint('lecture_id')
    )
    op.drop_column('lectures', 'avatar_backend')
    op.drop_column('lectures', 'seed')
    op.drop_column('lectures', 'started_at')
    op.drop_column('lectures', 'script_path')
    op.drop_column('lectures', 'completed_at')
    op.drop_column('lectures', 'output_video_path')
    op.drop_column('lectures', 'audio_cfg')
    op.drop_column('lectures', 'preset')
    op.drop_column('lectures', 'text_cfg')
    op.drop_column('lectures', 'error_message')
    op.drop_column('lectures', 'num_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('num_steps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('text_cfg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('preset', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('audio_cfg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('output_video_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('script_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lectures', sa.Column('seed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lectures', sa.Column('avatar_backend', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('lecture_pipelines')
    # ### end Alembic commands ###
