"""update schedule table 

Revision ID: f2d1c3e3b10c
Revises: 8d44f6a58adc
Create Date: 2026-01-20 14:58:57.765361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d1c3e3b10c'
down_revision: Union[str, Sequence[str], None] = '8d44f6a58adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'lecture_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('lecture_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
