/// Models for the Student Q&A feature.
///
/// Mirrors the FastAPI response shapes in app/api/v1/endpoints/qa.py:
///   POST  /{lecture_id}/ask      → QAAskResponse
///   GET   /{lecture_id}/history  → QAChatHistory  (list of QAMessage)
///   GET   /{lecture_id}/status   → QAIndexStatus
///   GET   /audio/{message_id}    → streamed bytes (no model needed)
///   DELETE /session/{session_id} → plain JSON message (no model needed)

// ─── Enums ────────────────────────────────────────────────────────────────────

enum QAMessageRole {
  user,
  assistant;

  static QAMessageRole fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'assistant':
        return QAMessageRole.assistant;
      case 'user':
      case 'student':
      default:
        return QAMessageRole.user;
    }
  }
}

enum QAIndexStatus {
  pending,
  ingesting,
  ready,
  failed;

  static QAIndexStatus fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'ingesting':
        return QAIndexStatus.ingesting;
      case 'ready':
        return QAIndexStatus.ready;
      case 'failed':
        return QAIndexStatus.failed;
      case 'pending':
      default:
        return QAIndexStatus.pending;
    }
  }
}

// ─── QAMessage ────────────────────────────────────────────────────────────────

/// A single chat message returned by the history endpoint.
class QAMessage {
  final int messageId;
  final int sessionId;
  final QAMessageRole role;
  final String content;
  final String? audioOutputPath; // set only for assistant messages
  final DateTime createdAt;

  const QAMessage({
    required this.messageId,
    required this.sessionId,
    required this.role,
    required this.content,
    this.audioOutputPath,
    required this.createdAt,
  });

  factory QAMessage.fromJson(Map<String, dynamic> json) {
    return QAMessage(
      messageId: (json['message_id'] as num?)?.toInt() ?? 0,
      sessionId: (json['session_id'] as num?)?.toInt() ?? 0,
      role: QAMessageRole.fromString(json['role'] as String?),
      content:
          json['content_text'] as String? ?? json['content'] as String? ?? '',
      audioOutputPath:
          json['audio_url'] as String? ?? json['audio_output_path'] as String?,
      createdAt: json['timestamp'] != null
          ? DateTime.tryParse(json['timestamp'].toString()) ?? DateTime.now()
          : json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => {
    'message_id': messageId,
    'session_id': sessionId,
    'role': role.name,
    'content': content,
    'audio_output_path': audioOutputPath,
    'created_at': createdAt.toIso8601String(),
  };
}

// ─── QAAskResponse ────────────────────────────────────────────────────────────

/// Shape returned by POST /{lecture_id}/ask.
///
/// Backend returns the student's question message + the assistant answer
/// message together so the UI can display both without a separate history
/// fetch.
class QAAskResponse {
  /// The question message saved to the DB (role = user).
  final QAMessage question;

  /// The answer message generated by the AI (role = assistant).
  final QAMessage answer;

  /// Optional URL to stream the TTS audio for the answer.
  /// Typically  /qa/audio/{message_id}  resolved by the service layer.
  final String? audioUrl;

  const QAAskResponse({
    required this.question,
    required this.answer,
    this.audioUrl,
  });

  factory QAAskResponse.fromJson(Map<String, dynamic> json) {
    // Backend returns flat: { message_id, session_id, answer_text, audio_url, timestamp }
    final sessionId = (json['session_id'] as num?)?.toInt() ?? 0;

    final answerMsg = QAMessage(
      messageId: (json['message_id'] as num?)?.toInt() ?? 0,
      sessionId: sessionId,
      role: QAMessageRole.assistant,
      content:
          json['answer_text'] as String? ??
          json['content_text'] as String? ??
          '',
      audioOutputPath: json['audio_url'] as String?,
      createdAt: json['timestamp'] != null
          ? DateTime.tryParse(json['timestamp'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );

    // The question is shown optimistically in the UI already,
    // so we build a placeholder here just to hold the session context.
    final questionMsg = QAMessage(
      messageId: 0,
      sessionId: sessionId,
      role: QAMessageRole.user,
      content: '',
      createdAt: DateTime.now(),
    );

    String? audioUrl;
    if (answerMsg.audioOutputPath != null &&
        answerMsg.audioOutputPath!.isNotEmpty) {
      audioUrl = '/qa/audio/${answerMsg.messageId}';
    }

    return QAAskResponse(
      question: questionMsg,
      answer: answerMsg,
      audioUrl: audioUrl,
    );
  }
}

// ─── QAChatHistory ────────────────────────────────────────────────────────────

/// Shape returned by GET /{lecture_id}/history.
class QAChatHistory {
  final int lectureId;
  final int? sessionId;
  final List<QAMessage> messages;
  final int page;
  final int pageSize;
  final int totalMessages;

  const QAChatHistory({
    required this.lectureId,
    this.sessionId,
    required this.messages,
    required this.page,
    required this.pageSize,
    required this.totalMessages,
  });

  factory QAChatHistory.fromJson(Map<String, dynamic> json) {
    final rawMessages = json['messages'] as List<dynamic>? ?? [];
    return QAChatHistory(
      lectureId: (json['lecture_id'] as num?)?.toInt() ?? 0,
      sessionId: (json['session_id'] as num?)?.toInt(),
      messages: rawMessages
          .map((e) => QAMessage.fromJson(e as Map<String, dynamic>))
          .toList(),
      page: (json['page'] as num?)?.toInt() ?? 1,
      pageSize: (json['page_size'] as num?)?.toInt() ?? 20,
      totalMessages:
          (json['total'] as num?)?.toInt() ??
          (json['total_messages'] as num?)?.toInt() ??
          0,
    );
  }
}

// ─── QALectureIndexStatus ─────────────────────────────────────────────────────

/// Shape returned by GET /{lecture_id}/status.
class QALectureIndexStatus {
  final bool isIndexed;
  final QAIndexStatus status;
  final DateTime? ingestedAt;
  final int? chunksIndexed;

  const QALectureIndexStatus({
    required this.isIndexed,
    required this.status,
    this.ingestedAt,
    this.chunksIndexed,
  });

  factory QALectureIndexStatus.fromJson(Map<String, dynamic> json) {
    return QALectureIndexStatus(
      isIndexed: json['is_indexed'] as bool? ?? false,
      status: QAIndexStatus.fromString(json['status'] as String?),
      ingestedAt: json['ingested_at'] != null
          ? DateTime.tryParse(json['ingested_at'].toString())
          : null,
      chunksIndexed: (json['chunks_indexed'] as num?)?.toInt(),
    );
  }
}
