# app/models/qa_session.py

from sqlmodel import Field, SQLModel, Relationship
from typing import Optional, List, TYPE_CHECKING
from datetime import datetime

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.lecture import Lecture
    from app.models.qa_message import QAMessage


class QASession(SQLModel, table=True):
    __tablename__ = "qa_sessions"

    id                     : Optional[int] = Field(default=None, primary_key=True)
    student_id             : int           = Field(foreign_key="users.user_id", index=True)
    lecture_id             : int           = Field(foreign_key="lectures.lecture_id", index=True)

    # Generated by backend: f"student_{student_id}_{lecture_id}"
    # Passed to RAG /query as student_session_id
    rag_student_session_id : str

    created_at             : datetime = Field(default_factory=datetime.utcnow)
    last_active_at         : datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    student  : Optional["User"]        = Relationship()
    lecture  : Optional["Lecture"]     = Relationship(back_populates="qa_sessions")
    messages : List["QAMessage"]       = Relationship(back_populates="session")